# Generated by Django 4.2.3 on 2023-12-07 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=25)),
                ('l_name', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=25)),
            ],
        ),
        migrations.DeleteModel(
            name='Students',
        ),
    ]
